/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorGeneric;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author opizarro
 */
public class VistaPolinomial extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaPolinomial
     */
    public VistaPolinomial() {
        initComponents();
        this.setClosable(true);
        setTitle("Polinomial");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInfectados = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        btnFallecidos = new javax.swing.JToggleButton();
        btnRecuperados = new javax.swing.JToggleButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInfectados.setText("Ver Infectados");
        btnInfectados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfectadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnInfectados, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 630, 370));

        btnFallecidos.setText("Ver Fallecidos");
        btnFallecidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFallecidosActionPerformed(evt);
            }
        });
        getContentPane().add(btnFallecidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        btnRecuperados.setText("Ver Recuperados");
        btnRecuperados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuperadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnRecuperados, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInfectadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfectadosActionPerformed
        /*ImageIcon polinomial = new ImageIcon(getClass().getResource("C:\\Users\\opizarro\\Documents\\OctaveProjects\\polinomial.jpg"));
        ImageIcon imgpol= new ImageIcon(polinomial.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
        jLabel1.setIcon(imgpol);*/
        
       String comando = "cd octave && C:\\Octave\\Octave-5.2.0\\mingw64\\bin\\octave.bat .\\polinomialc.m";
       ControladorGeneric.ejecutarComando(comando);
       
    }//GEN-LAST:event_btnInfectadosActionPerformed

    private void btnFallecidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFallecidosActionPerformed
        // TODO add your handling code here:
        String comando = "cd octave && C:\\Octave\\Octave-5.2.0\\mingw64\\bin\\octave.bat .\\polinomialf.m";
       ControladorGeneric.ejecutarComando(comando);
    }//GEN-LAST:event_btnFallecidosActionPerformed

    private void btnRecuperadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuperadosActionPerformed
        // TODO add your handling code here:
        String comando = "cd octave && C:\\Octave\\Octave-5.2.0\\mingw64\\bin\\octave.bat .\\polinomialr.m";
       ControladorGeneric.ejecutarComando(comando);
    }//GEN-LAST:event_btnRecuperadosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnFallecidos;
    private javax.swing.JToggleButton btnInfectados;
    private javax.swing.JToggleButton btnRecuperados;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
