/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author opizarro
 */
public class VistaDatos extends javax.swing.JInternalFrame {

    int m=0;
    /**
     * Creates new form Datos
     */
    public VistaDatos() {
        initComponents();
        this.setClosable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jspdatos = new javax.swing.JScrollPane();
        jtbdatos = new javax.swing.JTable();
        jbtverdatos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setTitle("Datos Covid-19 Italia");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Italia");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 770, 80));

        jtbdatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jspdatos.setViewportView(jtbdatos);

        getContentPane().add(jspdatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 860, 360));

        jbtverdatos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtverdatos.setText("Ver datos");
        jbtverdatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtverdatosActionPerformed(evt);
            }
        });
        getContentPane().add(jbtverdatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, -1, -1));

        jLabel3.setText(".");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 600, 20, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtverdatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtverdatosActionPerformed
        m=0;
        DefaultTableModel modelo=new  DefaultTableModel();
       jtbdatos.setModel(modelo);
       String titulo;
        for(int i=0;i<2;i++){
           if(i==0){
           titulo="Dias";
           modelo.addColumn(titulo);
           }
           else{
           titulo="Casos Confirmados";
           modelo.addColumn(titulo);
           }
        }
        modelo.setColumnCount(2);
        String linea;
        String[]valores;
        File archivo=new File("TotalCasos.csv");
        try {
            Scanner entrada=new Scanner(archivo);
            while(entrada.hasNext()){

                linea=entrada.nextLine();
                valores=linea.split(",");
                m++;
               
                modelo.addRow(valores);}
        } catch (FileNotFoundException ex) {
            Logger.getLogger(VistaDatos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtverdatosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbtverdatos;
    private javax.swing.JScrollPane jspdatos;
    private javax.swing.JTable jtbdatos;
    // End of variables declaration//GEN-END:variables
}
