/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author opizarro
 */
public class VistaDatos extends javax.swing.JInternalFrame {

    int m=0;
    /**
     * Creates new form Datos
     */
    public VistaDatos() {
        initComponents();
        this.setClosable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jspdatos = new javax.swing.JScrollPane();
        jtbdatos = new javax.swing.JTable();
        btnMore = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jbtverdatos1 = new javax.swing.JButton();

        setTitle("Datos Covid-19 Italia");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Italia");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        jtbdatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jspdatos.setViewportView(jtbdatos);

        getContentPane().add(jspdatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 860, 360));

        btnMore.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnMore.setText("Ver fuente");
        btnMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoreActionPerformed(evt);
            }
        });
        getContentPane().add(btnMore, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, -1, -1));

        jLabel3.setText(".");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 600, 20, -1));

        jbtverdatos1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtverdatos1.setText("Ver datos");
        jbtverdatos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtverdatos1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtverdatos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoreActionPerformed
        VistaPrincipal.goToURL("https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series");
    }//GEN-LAST:event_btnMoreActionPerformed

    private void jbtverdatos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtverdatos1ActionPerformed
        // TODO add your handling code here:
        m=0;
        DefaultTableModel modelo=new  DefaultTableModel();
       jtbdatos.setModel(modelo);
       String titulo;
        for(int i=0;i<2;i++){
           if(i==0){
           titulo="Dias";
           modelo.addColumn(titulo);
           }
           else{
           titulo="Casos Confirmados";
           modelo.addColumn(titulo);
           }
        }
        modelo.setColumnCount(2);
        String linea;
        String[]valores;
        File archivo=new File("datos/confirmados.csv");
        try {
            Scanner entrada=new Scanner(archivo);
            while(entrada.hasNext()){

                linea=entrada.nextLine();
                
                valores=linea.split(",");
                
                m++;
               String a [] = {m+"",valores[0]};
                modelo.addRow(a);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(VistaDatos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtverdatos1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbtverdatos1;
    private javax.swing.JScrollPane jspdatos;
    private javax.swing.JTable jtbdatos;
    // End of variables declaration//GEN-END:variables
}
